### ISSUE TITLE
Version 2.1.0 is good to go

### ISSUE THREAD

**Issue by swashata** [micc83/fontIconPicker#11]
Hello,

I have committed all necessary patches for version 2.1.0. I think it is ready to go live now. Please update the readme.md file while on the process.

**Comment by etcook** [comment]
Is 2.1 going to be merged into master, tagged and released?

**Comment by micc83** [comment]
Hi @etcook, as you can see we haven't been able to release updates in a while. At the moment I can't possibly merge the 2.1 as i'm really not up to date with the latest enhancement/bug fixes applied.
Hopefully in 2 weeks from now I should have a little time to check everything out and decide how to proceed. @swashata are you still able to follow the project?

**Comment by swashata** [comment]
Hi @micc83, I have had a really tough time last year with some serious family issues. Starting from this year, I had to get a hold on my commercial projects and I am left with a very little time. Hopefully after 10 of march, I might be able to look into this.

**Comment by micc83** [comment]
Hello @swashata I'm deeply sorry to hear that. I hope eventually everything went for the better. Take your time. Whenever you get some spare time we will talk about the future of the project but no rush.

Alex
