### ISSUE TITLE
Add option for SELECT OPTION

### ISSUE THREAD

**Issue by xavierfaucon** [micc83/fontIconPicker#15]
Hello,

When your icon list is constructed in the following way, where 'id' is the database id:

``` html
<option value="id">fa fa-search</option>
```

fontIconPicker is going to use the 'id' for the class, as below:

``` html
<i data-fip-value"..." class="id"></i>
```

Would that be possible to add an option to specify for SELECT tag to use the OPTION tag's value attributes or the text between OPTION and /OPTION

It would mean using 'flipBoxTitle' instead of 'item' in line https://github.com/micc83/fontIconPicker/blob/master/jquery.fonticonpicker.js#L640

What do you think?

**Comment by swashata** [comment]
With the intro of #39 I think this becomes useless as one can now render as needed. I will see if any other parameter needs to get exposed.

**Comment by swashata** [comment]
Closing as a future commit will expose `item, flipBoxTitle, i` to the renderer.
