### ISSUE TITLE
stupid question - only using fontawesome

### ISSUE THREAD

**Issue by WPThemer** [micc83/fontIconPicker#17]
Hi..

Thanks foe this amazing plugin, I am going to use it in one of my wordpress theme. However, I am a bit confused, I only want to use FontAwesome, is there any example which displays categorized fontawesome icons only ?

regards

**Comment by micc83** [comment]
Hello WPThemer. Unfortunately Fontawesome icons doesn't come with categories. The easiest way i can think of is to download Fontawesome from Fontello and customise the provided config file adding a category field to each icon then using that file to build a source Object to be passed to fontIconPicker.

    // Build an object like this from the Fontello config file
    var sourceIcons = {
        'Category 1' : ['icon-heart', 'icon-lemon'],
        'Category 2' : ['icon-user', 'icon-tag', 'icon-help']
    }
    
    // Then pass it to 
    $('.input').fontIconPicker({
        source: sourceIcons,
        emptyIcon: false,
        hasSearch: false
    });

**Comment by WPThemer** [comment]
Hi micc..

thanks for the reply..
Sorry for my ignorance, but is Fontello the same Library (Font Awesome) ?
secondly in my code I have the Font Awesome Codes like fa-gears instead of icon-gears, is there anything I need to change in CSS files...

regards

**Comment by micc83** [comment]
Fontello is an icon fonts bundle generator http://fontello.com/

If you'll go for fontello no problem as all the icons name will be changed to icon-* otherwise i guess you can use the "fa fa-*" syntax on the sourceIcons Object.

**Comment by WPThemer** [comment]
ok Thanks.. I will try and get back here...

thanks once again... cheers
