### ISSUE TITLE
loading in wordpress thickbox..

### ISSUE THREAD

**Issue by WPThemer** [micc83/fontIconPicker#18]
hi micc again, sorry for posting another question.. please bear with me as I love your plugin and want to use it in one of my theme that I have been working over 8 months now..

I have successfully created a working example with <input> field on the localhost.. which works perfectly except it does not show the pagination and dropdown icon... but it shows the Fontawesome icons perfectly...

however when loading it in Thickbox (using Zilla Shortcode plugin) it converts the inputbox to a working iconPicker but it doesnt show any icons, I checked the code, its perfectly added everything, but simply doesnt show the fontawesome icons, I put the2 icons before the inputbox to see if there is something wrong with Fontawesome, but those icons how perfectly... what could possible be wrong ? am still digging..

regards

![font_picker](https://cloud.githubusercontent.com/assets/6549749/6547259/dd8758a4-c5ec-11e4-9fe6-bac1dfe19255.png)

**Comment by WPThemer** [comment]
Please ignore the second icon as I removed the class and IDS through firebug for testing...

**Comment by micc83** [comment]
There's no much I can do without being able to check the actual working code. If you publish the example online I'll check it out.

Cheers,
Alex

**Comment by shivapoudel** [comment]
@WPThemer how you have implemented is important. May be I could help you if I couldn't know how you have done :P
