### ISSUE TITLE
selected option is not updated when an icon is picked

### ISSUE THREAD

**Issue by DemarsM** [micc83/fontIconPicker#20]
If the <option> got a value attribute, selected option is not updated when an icon is picked

Not working:

            <select>
                <option value="1">icon-airfield</option>
            </select>

Working:

            <select>
                <option>icon-airfield</option>
            </select>

You can see it here: https://jsfiddle.net/5m9wco4b/5/

**Comment by micc83** [comment]
Well, that's actually how it's supposed to work. The value of the option MUST be the same of the icon class name. What exactly are you trying to achieve here?

**Comment by DemarsM** [comment]
ok this is good to know that! 

In my case, each icon is referenced with an object in the database. The value of the option is the pk of that object in order to be able to retrieve the selected object on server side when the form is submitted.

Would it be possible to achieve that?

**Comment by micc83** [comment]
I guess you could add a data-id attribute to each option and retrieve that
instead of the value/text...
Il 23/mar/2015 13:02 "Maxime Demers" <notifications@github.com> ha scritto:
