### ISSUE TITLE
Missing icons. Comma showing as icons class. 

### ISSUE THREAD

**Issue by danyj** [micc83/fontIconPicker#23]
I just downloaded custom pack from IcoMoon and in seletcion.json the  icon name is 

    clipboard, paste

that icon as well as many other are missing in the list since the class contains the comma. 

http://prntscr.com/8jkybk

**Comment by swashata** [comment]
Hello,

I actually realized the issue with the icon indexer PHP toolkit and fixed it too. You may check the indexer now https://github.com/swashata/IcoMoonIconIndexer/releases/tag/v1.1.0

I have plans to update this library when I get some time.
