### ISSUE TITLE
After load success，how do I select an icon by default？

### ISSUE THREAD

**Issue by HyramTang** [micc83/fontIconPicker#29]
After loading the page, how do I select an icon by default？
the default icon come from database.

**Comment by micc83** [comment]
Not sure what are you asking. I mean, in order to set a default icon you would proceed as you would with any other input field:
```html
<select id="myselect" name="myselect" class="myselect">
    <option value="">No icon</option>
    <option>...</option>
    <option selected>icon-search</option>
    <option>...</option>
</select>
```
or
```html
<input type="text" name="mytext" id="mytext" value="icon-search" />
```
or if you need to do it on the fly:
```js
var $picker = $('#e1_element').fontIconPicker();
$picker.val('icon-search').refreshPicker();
```
Hope that helps.

Cheers,
Alex

**Comment by HyramTang** [comment]
I used font-awesome icon can't run，can you support font-awesome icon？:smile:

**Comment by micc83** [comment]
Fontello uses Font Awesome v4.7.0.
