### ISSUE TITLE
SVG Icon Support & FontAwesome Example

### ISSUE THREAD

**Issue by migliori** [micc83/fontIconPicker#41]
Hi,

Thanks for this great work. Just a very very minor change request to accept svg icons for icomoon, font awesome and others: I had to edit the selector to get the selected icon in jquery.fonticonpicker.js L.428:

```
$(e.currentTarget)
.find('i, svg') // instead of .find('i')
.attr('data-fip-value')
```
I thought it may be useful for other users.

2nd thing: I built a [JSON list with all the Font Awesome Icons categorized](https://gist.github.com/migliori/60154172ba0eea70e3c0dd4c3b5d82d0), feel free to use it and maybe add an example https://codeb.it/fonticonpicker/:

**Comment by swashata** [comment]
Thanks.. I will definitely keep this in mind.

**Comment by swashata** [comment]
@migliori if you can, keep an eye on the 3.0.0 branch. I will see if I can incorporate such feature.

**Comment by migliori** [comment]
Thanks, I'm waiting for 3.0

**Comment by migliori** [comment]
Thanks, great.
