### ISSUE TITLE
Suggestion for moving into org repository

### ISSUE THREAD

**Issue by swashata** [micc83/fontIconPicker#46]
Hello @micc83 

I have a small suggestion to make. Would it be okay if we move fontIconPicker to a separate organization account? The reason why I am asking this

1. It will be synced with [npm organization](https://www.npmjs.com/org/fonticonpicker)
2. I am learning react right now. Once done, I will create a better doc with react and material ui (will also make fip react compatible and have material themes). We can seamlessly publish it as github pages and get a custom domain from `js.org`.

Let me know what you think.

**Comment by swashata** [comment]
@micc83 

I don't have any issue with that. I would go with an organization and add you as a member. 

But really why can't you have fontIconPicker under an organization and have it on your resume as well? On your profile page, it will show loud and clear you are owner/admin of the organization 😝.

But if you insist the other way, I totally understand.

**Comment by micc83** [comment]
Hello @swashata ,
That's exactly why I would rather that you start a new repo for version 3 as the owner. As on the organization you'll be in charge, not me. If you want me as a member I would be honored to contribute as I can but it is simply not fair that I would still be the owner.
Glad you understood my reasons. Let me know as soon as the new repo is ready and I'll update the documentation accordingly. You're obviously free to edit the readme on the master branch yourself.

**Comment by swashata** [comment]
I will rather create the org, add you as a member and leave it up to you to make changes elsewhere. For old time's sake. 😃

**Comment by swashata** [comment]
Hi @micc83 ,

I have created an org here https://github.com/fontIconPicker/fontIconPicker and have added you as well. Further development will go over there.

**Comment by swashata** [comment]
@micc83 

Could you please do me a favor and move issues to the new repo? https://github-issue-mover.appspot.com/

I tried but since I am not the owner of this, it refused. You are already an owner of the org so you should be able to do it.

**Comment by micc83** [comment]
Done 😄

**Comment by swashata** [comment]
thanks...
