### ISSUE TITLE
Release v3.0.0

### ISSUE THREAD

**Issue by swashata** [micc83/fontIconPicker#47]
Hello @micc83,

Finally v3.0.0 is out 🍺🍪... You may now update the links 👍 

https://github.com/fontIconPicker/fontIconPicker

**Comment by micc83** [comment]
Well done 🍻🍺! I'll do it tomorrow morning as soon as I get to the office!

**Comment by swashata** [comment]
Man I must thank @wesbos and his tutorials for this. I guess I am finally certified to download the ES6 certificate 😁

**Comment by swashata** [comment]
@micc83 how you doing? Just wanted to tell you that I have create a react version as well http://fonticonpicker.github.io/react-fonticonpicker/ Have a look when you get a change ;)

**Comment by micc83** [comment]
Hello @swashata sorry for letting you down. I've updated the readme file and I'm updating the documentation page as well. However I see that the script url on the CDN is down on https://fonticonpicker.github.io/. Could you please check so that I can safely update the doc page?
Cheers

**Comment by swashata** [comment]
@micc83 no worries at all. I think I need to put in tagged CDN url, instead of untagged ones. I will update and let you know.
