### ISSUE TITLE
Icon picker

### ISSUE THREAD

**Issue by rpsrps** [micc83/fontIconPicker#48]
Dear Micc83, Can you help me to select different icons than what i have.

Can i upload other icons than the icons i have. I use your iconpicker in the administration system from wordpress. 
<img width="608" alt="iconpicker screenshot" src="https://user-images.githubusercontent.com/42641383/44523141-2abddc80-a6d9-11e8-91fa-7fe54dcbf149.PNG">

**Comment by khanzadimahdi** [comment]
see [this gist](https://gist.github.com/khanzadimahdi/5f0e9327f1c7abe551f043b3f9259d63).
