### ISSUE TITLE
Themes not working? Not default theme either? 

### ISSUE THREAD

**Issue by kaizokupuffball** [micc83/fontIconPicker#49]
I have this very weird problem as the picker won't show up with any styles. 
It's just all white. 
I've checked that all the css files are loaded properly in the browser, and they are.

The css i include are theese:
`jquery.fonticonpicker.min.css`
`jquery.fonticonpicker.grey.min.css`
`jquery.fonticonpicker.bootstrap.min.css`

And it still looks like this: 
![bilde](https://user-images.githubusercontent.com/4356128/68790099-f5d3d780-0646-11ea-94e0-0f31f5924a79.png)

Here is the code i use to instantiate the icon picker:
`            var fontIconPickerInput = $('#fontIconPicker');
            fontIconPickerInput.fontIconPicker({
                emptyIcon: false,
                source: ['fas fa-heart', 'fas fa-search', ' fas fa-user', 'fas fa-tag', 'fas fa-help'],
                theme : 'grey'
            });
`

Am I missing something here? 
I also tried adding some style to the `.selector` class, but it doesn't show either.
I don't know what I am doing wrong here.

**Comment by micc83** [comment]
Hello @kaizokupuffball, unfortunately v2 is not supported anymore. Checkout v3 at https://github.com/fontIconPicker/fontIconPicker.
