### ISSUE TITLE
Ideas for future

### ISSUE THREAD

**Issue by swashata** [micc83/fontIconPicker#5]
Since we are good to go with version 2.0.0, here are my ideas for future release:
- [ ] Make the plugin APIs more like widgets. Instead of having to save the reference in a variable, I think something like this would be a better approach: `$('.mypicker').fontIconPicker('setIcons', newSource, newSearch)` This will require major structure rewrite.
- [ ] Support for HTML `data-attr` for having inline options. Like `<input source="['icon-1', 'icon-2']" />`
- [ ] Custom events triggered when the picker opens, closes, user chooses an icon, makes search etc. So that others can hook in.
- [ ] A new API to set & get individual options. Something like:  `$('.mypicker').fontIconPicker('options', 'theme', 'fip-grey'); // Setter` & `$('.mypicker').fontIconPicker('options', 'theme'); // Getter`
- [ ] Ability to categorize icons on the fly from config or selection json files based on user provided tags. I can adapt to the logic used in IconIndexer script.

This is all I can think of now.

**Comment by DemarsM** [comment]
Possibility to choose a position such:

        1 2 3 4 5
        G       6
        F       7
        E       8
        D C B A 9

    0.      inline (no placement, display as inline-block)
    1.      topLeftCorner
    2.      topLeft
    3.      top (center)
    4.      topRight
    5.      topRightCorner
    6.      rightTop
    7.      right (center)

**Comment by micc83** [comment]
This issue was moved to fontIconPicker/fontIconPicker#5
