### ISSUE TITLE
Create tag v3.0

### ISSUE THREAD

**Issue by timdiels1** [micc83/fontIconPicker#50]
Hi,

I see there is a v3.0 out, but there is no release tag? This makes it that there is no stable release on https://asset-packagist.org/package/bower-asset/fonticonpicker and we use this to get the package in our projects.

Could you please make a v3.0 release tag?

Thank you

**Comment by micc83** [comment]
Hello @timdiels1, as stated in the documentation the project moved to https://github.com/fontIconPicker/fontIconPicker. There you'll find v3 tags.
