### ISSUE TITLE
Wrong value set when the select value is emptyIconValue and emptyIconValue is not ""

### ISSUE THREAD

**Issue by swashata** [micc83/fontIconPicker#7]
Already working on a solution. Will fix in 2.1.0 branch.

**Comment by danyj** [comment]
This is not right 
https://github.com/micc83/fontIconPicker/blob/2.1.0/jquery.fonticonpicker.js#L672

it is  setting  the selected icon to empty  on category change without user selecting an icon. 

if   emptyIcon  is set to false than it is resetting the selected icon to the first icon in the category, again without user clicking on any icons
